### ISSUE TITLE
(1.3) Loading Error for Industriousness:n traits

### ISSUE THREAD

**Issue by nighthawkuofl** [GarwelGarwel/Rimocracy#72]
Seems to be an issue with the /Defs/ProtestDefs/Protests.xml file changed in the past few days (presumably for 1.4). Stack trace (one of twelve) below:

Could not resolve cross-reference: No RimWorld.TraitDef named Industriousness:2 found to give to Rimocracy.Consideration Rimocracy.Consideration
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch5 (string)
Verse.DirectXmlCrossRefLoader/WantedRefForObject:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>c__DisplayClass15_1:<ResolveAllWantedCrossReferences>b__0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>c__DisplayClass7_1`1<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b__0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

**Comment by GarwelGarwel** [comment]
Thanks for the report. Fixed it (hopefully) in v1.4.2. Please reopen the issue if you still encounter the problem.
